clonealign_data_url: https://zenodo.org/record/2363826/files/clonealign-processed-data.tar.gz
ov2295_cnvs_url: https://zenodo.org/record/5725635/files/ov2295_clone_cn.csv.gz
ov2295_clusters_url: https://zenodo.org/record/5725635/files/ov2295_clone_clusters.csv.gz
cnv_max: 8
autosomes_only: true
scatrex:
  n_tries: 10
  n_iters: 5000
  n_factors: 4
plotting:
  dpi: 100
  cellstate_cmap: "PRGn"
  axislabel_fontsize: 14
  tick_fontsize: 14
  boxplot_width: 8
  boxplot_height: 5
  cnv_matrix_width: 8
  cnv_matrix_height: 5
  nodelabel_fontsize: 14
  nodesize_fontsize: 12
