output_path: /Users/pedrof/projects/SCATrEx/workflows/benchmark/results
scripts_path: /Users/pedrof/projects/SCATrEx/scripts
n_clones: 3
n_genes: 800
n_cells: 1000
n_reps: 10
n_tries: 3
methods:
 - correlation
 - clonealign
 - leiden
 - clonealign_leiden
 - scatrex
